<a href="https://colab.research.google.com/github/sarithamiryala/ANN_implementation/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.17.0'

## Tensor Constant

In [7]:
const = tf.constant(10)

In [8]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=10>

JAX : Built on Numpy but it supports CUDA

In [9]:
# for Specific datatype

const = tf.constant(43,dtype=tf.float32)

In [10]:
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [11]:
const.numpy()

43.0

In [12]:
const_mat = tf.constant([[1,3],[4,5]],dtype=tf.float32)

In [13]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 5.]], dtype=float32)>

In [14]:
const_mat.shape

TensorShape([2, 2])

In [15]:
const_mat.dtype

tf.float32

In [17]:
const_mat[0][1]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [18]:
const_mat[0][0]=32

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#Commonly used methods

In [19]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
-1*tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [21]:
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# ADD Operation

In [25]:
const1 = tf.constant([[1,2,3],[4,5,6]])
const2 = tf.constant([[2,3,5],[4,5,6]])

In [26]:
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  5,  8],
       [ 8, 10, 12]], dtype=int32)>

In [27]:
tf.add(const1,const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  5,  8],
       [ 8, 10, 12]], dtype=int32)>

In [28]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.8985935 , 0.6278246 ],
       [0.43701023, 0.08419178]], dtype=float32)>

In [29]:
tf.random.uniform(shape=(2,2),minval=0,maxval=20)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 9.159328 , 14.276554 ],
       [10.480428 ,  5.5599236]], dtype=float32)>

#Variables

In [30]:
var1 = tf.Variable([[1,2,3],[4,5,6]])
var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [31]:
var1[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [34]:
var2 = tf.Variable(43)
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=43>

In [35]:
var2.assign(23)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=23>

In [36]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [38]:
var1.assign([[5,2,3],[4,5,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [39]:
var1[1,1].assign(22)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  2,  3],
       [ 4, 22,  6]], dtype=int32)>

# Reshaping Operation

In [40]:
tensor = tf.Variable([[1,2,3],[4,5,6]])

In [41]:
tensor.shape

TensorShape([2, 3])

In [42]:
tf.reshape(tensor,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [43]:
tf.reshape(tensor,shape=(1,6))

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [44]:
tf.reshape(tensor,shape=(6,1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

# Other mathematical Operations

In [45]:
var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  2,  3],
       [ 4, 22,  6]], dtype=int32)>

In [47]:
tf.square(var1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 25,   4,   9],
       [ 16, 484,  36]], dtype=int32)>

In [50]:
tf.pow(var1,2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 25,   4,   9],
       [ 16, 484,  36]], dtype=int32)>