<a href="https://colab.research.google.com/github/sarithamiryala/ANN_implementation/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [2]:
tf.__version__

'2.17.0'

## Tensor Constant

In [7]:
const = tf.constant(10)

In [8]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=10>

JAX : Built on Numpy but it supports CUDA

In [9]:
# for Specific datatype

const = tf.constant(43,dtype=tf.float32)

In [10]:
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [11]:
const.numpy()

43.0

In [12]:
const_mat = tf.constant([[1,3],[4,5]],dtype=tf.float32)

In [13]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 5.]], dtype=float32)>